fix missing license file
Fix the build failing with the following error

    Error:   × No license files were copied

The COPYING file is located in the src/ subdirectory. This only recently
started failing as rattler-build recently enabled checking for missing
license files[1].

[1] https://github.com/prefix-dev/rattler-build/pull/1727